### ISSUE TITLE
doesn't work properly with youtube

### ISSUE THREAD

**Issue by csmart** [kororaproject/kp-mozilla-flashblock#1]
with flash installed, youtube doesn't work properly because they have defaulted to html5. with flash installed you get a play button but can't click to play. without flash you get blocked video but sound plays.

Seems only solution is to whitelist youtube as the bug report hasn't been fixed in ages:
https://www.mozdev.org/bugs/show_bug.cgi?id=25822

user_pref("flashblock.whitelist", "youtube.com");

**Comment by firnsy** [comment]
I've seen two posts prefer "s.ytimg.com" over "youtube.com"

**Comment by csmart** [comment]
@firnsy I tested tthu's package and youtube.com seems to work, also the doco seems to suggest using that cause it has some smarts about where the vids stream from. Anyway if that's not enough we can always push an update.
